<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ls</groupId>
        <artifactId>ls-aegis-server</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ls-aegis-rbac</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>认证登录、用户/角色/菜单/部门/字典/审计日志</description>

    <dependencies>
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-starter</artifactId>
        </dependency>
        <!-- 用户头像上传、社交登录消息等跨域能力 -->
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-biz-file</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-biz-notice</artifactId>
        </dependency>
        <dependency>
            <groupId>top.continew.starter</groupId>
            <artifactId>continew-starter-trace</artifactId>
        </dependency>
    </dependencies>
</project>
