<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ls</groupId>
        <artifactId>ls-aegis-server</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ls-aegis-security</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>Sa-Token、JWT、用户上下文、权限拦截、控制器基类</description>

    <dependencies>
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>top.continew.starter</groupId>
            <artifactId>continew-starter-auth-satoken</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-sign</artifactId>
        </dependency>
        <dependency>
            <groupId>top.continew.starter</groupId>
            <artifactId>continew-starter-auth-justauth</artifactId>
        </dependency>
    </dependencies>
</project>
