<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ls</groupId>
        <artifactId>ls-aegis-server</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ls-aegis-redis</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>Redis 配置、序列化、分布式锁、缓存工具封装</description>

    <dependencies>
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-common</artifactId>
        </dependency>
        <dependency>
            <groupId>top.continew.starter</groupId>
            <artifactId>continew-starter-cache-jetcache</artifactId>
        </dependency>
        <!-- JetCache valueEncoder=kryo5 需要 com.esotericsoftware.kryo.kryo5.Kryo -->
        <dependency>
            <groupId>com.esotericsoftware.kryo</groupId>
            <artifactId>kryo5</artifactId>
            <version>5.6.2</version>
        </dependency>
    </dependencies>
</project>