<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ls</groupId>
        <artifactId>ls-aegis-server</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ls-aegis-boot</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>启动入口模块：main 方法、主配置文件</description>

    <properties>
        <main-class>com.ls.aegis.boot.LsAegisApplication</main-class>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-rbac</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-biz-file</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-biz-notice</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-biz-open</artifactId>
        </dependency>
        <!-- 租户管理 API；行级隔离仍由 continew-starter.tenant.enabled 控制（默认 false） -->
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-biz-tenant</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ls</groupId>
            <artifactId>ls-aegis-biz-schedule</artifactId>
        </dependency>
        <dependency>
            <groupId>top.continew.starter</groupId>
            <artifactId>continew-starter-trace</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>ls-aegis-server</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>${main-class}</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
